### ISSUE TITLE
Unable to clean up cloudformation stack

### ISSUE THREAD

**Issue by tnachen** [heptio/aws-quickstart#41]
When trying to delete a stack that was created, it always seems to be stuck in cleaning up the VPC and subnets:

14:06:14 UTC-0800	DELETE_FAILED	AWS::CloudFormation::Stack	test-stack	The following resource(s) failed to delete: [VPC].
Physical ID:arn:aws:cloudformation:us-east-1:118478918310:stack/test-stack/27655af0-02a6-11e7-9cab-500c286e1a36
14:06:12 UTC-0800	DELETE_FAILED	AWS::EC2::VPC	VPC	The vpc 'vpc-92dc9ff4' has dependencies and cannot be deleted.

The stack was created with 4 nodes and all default settings.

However, I can go to the VPC page to delete the VPC manually, and then the subsequent delete will succeed.

**Comment by timothysc** [comment]
@tnachen thx for submitting ;-) 

We'll look into it shortly.

**Comment by tnachen** [comment]
@timothysc Thanks! Great work btw :)

**Comment by timothysc** [comment]
Thx, but other folks deserve the credit here..

**Comment by bchav** [comment]
@tnachen 

Did you have Kubernetes create an ELB for you (create a service with type loadbalancer) or is this just the default cluster?

**Comment by kensimon** [comment]
@tnachen 

Ah yes, this is a known issue at the moment... the AWS cloud provider in Kubernetes is responsible for creating load balancers when you create services with "type=LoadBalancer", but when it does so, it doesn't tag the resources with the CloudFormation stack... so they end up not getting deleted with the rest of the stack.  Particularly they create Network Attachments that are still active when the subnet gets deleted.

At least, that's the theory.  Did you create any Service objects in kubernetes that would have created an ELB load balancer?

**Comment by tnachen** [comment]
I did ask K8s to create a ELB for me, though I remember trying to delete them as well with k8s.

**Comment by kensimon** [comment]
Ok, yeah that jibes pretty well with my experience.  Not sure if it's due to a lack of tagging or not, it's just my best current theory.  I seem to remember an issue filed to the AWS cloud provider about this but I'm unable to find it.

I'll do some digging to try and validate my theory here at least.  Thanks for filing this.

**Comment by bchav** [comment]
@kensimon Cloudformation won't clean up resources it didn't create. 

In this case, the only workaround I can see is if there was a Cloudformation option for the AWS provider that used stack updates to add additional resources. We might need to look for an out of band solution to this. 

In the meantime, manually delete your kubernetes-created ELBs before deleting your stack and everything should clean up gracefully :)

**Comment by kensimon** [comment]
Is there a way (through tags or otherwise) to "trick" CloudFormation into thinking it owns the resources?  If not, there's probably not much we can do, other than maybe having the AWS cloud provider use cloudformation itself to create the resources (perhaps if it detects it's running in a CF stack.)

But I think I've seen issues where even after deleting the Services through kubectl, it still wasn't able to clean up the stack.  It's possible there's things that aren't getting cleaned up (I think it was a VPC gateway attachment, IIRC) when a Service is removed.

**Comment by bchav** [comment]
Unfortunately not, CFN uses the reserved `aws:` namespace for this purpose. 

It's possible to get hung up on sporadic gateway detach problems when deleting stacks, but I haven't run into it with this template. IIRC, the workaround would be to give the "GatewayAttachment" object an explicit dependency on the IGW. This ensures the attachment is created after the IGW, but also on teardown the attachment will be deleted before the IGW. If you can reproduce this, let's create a separate issue and work through it.

**Comment by kensimon** [comment]
After trying for a while, I'm unable to reproduce this if I clean up items in k8s before stack deletion.  Each time I've had this problem it's typically due to services or volumes not being cleaned up before deletion time.

Would a simple script that cleans up all resources from the k8s cluster be helpful here?  I think it would be of limited use however, since typically by the time you notice your stack won't delete, it's too late to talk to the k8s API any more (since it's probably already gone.)

**Comment by robertojrojas** [comment]
Does it make sense to add some instructions as part of the Next Step tutorials indicating what steps to follow to cleanly remove the deployed Stack? In my case, I followed some of the suggestions on this issue and the Stacks appeared to be deleted cleanly. Maybe the same suggestions could be used as a starting point for the instructions. As added bonus, they could be buy you some time to come up with an automated solution. ;)

**Comment by tnachen** [comment]
We worked around this by making sure that all the ELB deletes and associated security groups deletion is finished (as it happens async, so can't just delete k8s and then right away deleting the stack).

**Comment by kensimon** [comment]
Added a troubleshooting guide here that outlines how to delete the LB's: https://github.com/heptio/aws-quickstart/blob/master/troubleshooting.md

Since there's not much we can do to fix the real issue, documentation is the best we can do.
