### ISSUE TITLE
Add Elasticsearch instance to QS

### ISSUE THREAD

**Issue by kstewart** [heptio/aws-quickstart#47]
As we work towards making the AWS QS more production-ready, we believe we should add an AWS-hosted ElasticSearch instance. This would allow us to host fluentd/kibana on a QS cluster and have it be supported.

**Comment by kensimon** [comment]
Notes:

- AWS's ElasticSearch service requires some hoops to jump through for auth, I explored some options and it looks like [aws-signing-proxy](https://github.com/cllunsford/aws-signing-proxy) is a good bet.  I have a prototype cluster up with that as a service running in kube-system, with the fluentd DaemonSet configured to hit it as an endpoint.  With that I have a working EFK stack.

- Need to think about where we create the AWS ES doamain.  I think just creating an AWS::Elasticsearch::Domain in the k8s template will work for now, maybe with some options for how big it should be, etc.  Other potential options are to have the VPC stack create the ES domain and for it to pass that information to the k8s stack (although that gets tricky since IAM roles need to be passed between them for auth to work.)

- Creating the fluentd DaemonSet is pretty trivial, as is creating the aws-signing-proxy service, those should be no problem.

**Comment by kensimon** [comment]
More:

We can document a simple way to get to the kibana UI using `kubectl port-forward` to the proxy, which seems to work well:

```
$ kubectl -n kube-system port-forward aws-es-proxy-2517879486-2cv8l 8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```

![image](https://cloud.githubusercontent.com/assets/378280/24022129/caddf2ce-0a61-11e7-8cd0-d06c19a34da0.png)

**Comment by kensimon** [comment]
Closing this because the decision was to document how to do this instead: http://docs.heptio.com/content/tutorials/elastic.html
