### ISSUE TITLE
CloudFormation template not loading in CF designer

### ISSUE THREAD

**Issue by e30chris** [heptio/aws-quickstart#50]
_Description:_
Loading the Heptio CloudFormation template into the CF Designer so that I could edit and modify the template to fit my infrastructure, returns an error.  

Using this CF template in the AWS web console succeeds successful in building the k8s stack. 

_Repro Steps:_
- Open CF Designer
- Click Open
- Choose the 'Amazon S3 Bucket' option
- Choose the 'Template URL' option
- Paste the following Heptio S3 bucket CF template URL:
'https://s3.amazonaws.com/quickstart-reference/heptio/latest/templates/kubernetes-cluster-with-new-vpc.template'
- Click open

![screen shot 2017-03-23 at 5 24 08 pm](https://cloud.githubusercontent.com/assets/716387/24275608/e7d76fcc-0fed-11e7-8c5e-0967ff0f644c.png)

_Expected Behavior:_
- Heptio CF template loads into the Designer
- I am able to edit the CF template using the Designer

_Actual Behavior:_
- Error returned:

```
 3/23/2017, 5:26:01 PM - Currently the only language Designer supports is JSON. Cannot render this template because it is not valid JSON.: SyntaxError: JSON Parse error: Unrecognized token '#'
```

![screen shot 2017-03-23 at 5 28 14 pm](https://cloud.githubusercontent.com/assets/716387/24275636/27c3aaba-0fee-11e7-9d56-cdbdd7775e96.png)

Let me know if you need anything else to troubleshoot this bug.  I am here to help out in anyway I can.

**Comment by e30chris** [comment]
aaannnnnnndddd........read the docs first!

sorry and apologies - this is not a bug.  Designer only renders JSON and this is YAML.  My mistake!

the Designer docs clearly state:

```
Important
AWS CloudFormation Designer supports only JSON-formatted templates. Don't use YAML-formatted templates.
```

closing.

**Comment by kensimon** [comment]
Ah, you closed right as I was about to respond with mostly the same thing.

We had to make a judgement call right in the beginning whether we wanted to go with JSON or YAML, and we decided to go with YAML because it's easier to document (you can have inline comments), and AWS's tooling was starting to adopt it across the board.  Looks like the graphical designer still doesn't support it yet.

Unfortunately it's not as simple as doing a YAML->JSON conversion either, since some of the function intrinsics we're using (`!Ref`, `!Sub`, etc) are taking advantage of a syntax that only works in YAML.  So for now the only thing to do is to wait until AWS adopts YAML for their designer.

**Comment by e30chris** [comment]
As an "Ansible" person, we love our YAML, well most of the time.  Sorry again for the distraction and looking forward to continuing to work with Heptios k8s tooling.
