### ISSUE TITLE
Make the bastion UX completely Automated

### ISSUE THREAD

**Issue by jayunit100** [heptio/aws-quickstart#72]
The bastion could do with a few minor improvements.  Here's some suggestions I have...  After doing this, basically the heptio quickstart can be used by and kubernetes QA or app developer to deploy a non-trivial, working cluster out of the box.

- I think the bastion server and the master both do not expose a port for https.  Should we manually open them up?
- Automatically exporting KUBECONFIG in the environment variable for the apiserver might be a nice touch for users so they don’t have to do it themselves the first time they are checking that the cluster works.
- No kubernetes service dashboard , seems like that should be deployed in the quick start as well, this is redundant to  #71 but I guess how the bastion exposes this is what we shoudldecide here. 
- Ssh keys for the bastion to ssh into the internal nodes – since it appears like that’s the way that we expect to interact with the cluster?
- Expose the kubernetes API server, as well as the bastion, on a publically available IP.  Right now its hidden.
- Run a basic smoke test that confirms networking and port exposure is as it should be.
- Should we consider installing kubectl on the bastion so that users don't have to ssh at all into the apiserver ?

**Comment by kensimon** [comment]
Sorry it took a while for me to see this, let me respond to each item:

> I think the bastion server and the master both do not expose a port for https. Should we manually open them up?

There shouldn't be a reason to have the bastion expose HTTP, it only exists as a single host you SSH through if you want to get to the rest of the clutser.  HTTP(S) is exposed via an ELB that listens on the public internet (filtered by the same CIDR range you specify for the bastion, for convenience), not through the bastion host.

> Automatically exporting KUBECONFIG in the environment variable for the apiserver might be a nice touch for users so they don’t have to do it themselves the first time they are checking that the cluster works.

I think you mean on the master node, if you're SSH'd in, it'd be nice to have kubectl work out of the box.  I agree, we should copy that file to ~/.kube/config (the default location) on that node.  But we don't think that most people should be SSH'ing at all to manage their cluster, they should be copying the cluster config to their local machine (ie. their laptop) and talking directly through the kubernetes API remotely.  `kubectl proxy`, `exec`, everything still work since it's done through the HTTP API, not through SSH.

> No kubernetes service dashboard , seems like that should be deployed in the quick start as well, this is redundant to #71 but I guess how the bastion exposes this is what we shoudldecide here.

Yup, that'll be in the next release, which we're testing now (I hope to have a PR today.)

> Ssh keys for the bastion to ssh into the internal nodes – since it appears like that’s the way that we expect to interact with the cluster?

The expected way to interact would be by copying the kubeconfig from the master to your local machine and using kubectl locally.  The cloudformation output `GetKubeConfigCommand` gives you an scp command that goes through the bastion host and gets your kubeconfig for you.

> Expose the kubernetes API server, as well as the bastion, on a publically available IP. Right now its hidden.

It's exposed, but it's not in any direct output you can see.  If you need to know it, you can look at the kubeconfig file under `clusters` -> `- cluster` -> `server`. It's an ELB address so it's randomly generated.

> Run a basic smoke test that confirms networking and port exposure is as it should be.

This is done by kubeadm as part of the initialization, we don't have any plans to implement anything beyond that.

> Should we consider installing kubectl on the bastion so that users don't have to ssh at all into the apiserver ?

Maybe, but that's not currently the goal... I think we want to stay away from being too opinionated about what tooling gets onto the bastion, although it's possible `kubectl` would be a good bare minimum.  It's an interesting idea at least.
