### ISSUE TITLE
Prevent access to AWS metadata endpoint

### ISSUE THREAD

**Issue by mattmoyer** [heptio/aws-quickstart#73]
The EC2 metadata service provides instance role credentials via a link local interface (`http://169.254.169.254/latest/meta-data/iam/security-credentials/*`). This means any code running on the instance, even non-root code or code running inside a container, has access to whatever IAM role is assigned to the instance. Even without assuming malicious code, this data can be exposed by [Server Side Request Forgery (SSRF)](https://www.owasp.org/index.php/Server_Side_Request_Forgery) vulnerabilities.

We should block code in containers from accessing the metadata service. We probably want to block by network namespace or interface. This is similar to [what kube2iam does](https://github.com/jtblin/kube2iam#iptables).

**Comment by rdodev** [comment]
Given this: https://twitter.com/kennwhite/status/923615476340707331

Can we bump priority on this?

**Comment by timothysc** [comment]
Enqueue for next revision.

**Comment by timothysc** [comment]
@rdodev @mattmoyer - patches welcome too btw ;-)

**Comment by bgeesaman** [comment]
I believe you have two options (not mutually exclusive):

1. Install [kube2iam](https://github.com/jtblin/kube2iam) or [kiam](https://github.com/uswitch/kiam) to serve as a metadata proxy/filter (GCE/GKE has the GCE Metadata Proxy)
2. Implement egress ```networkpolicy``` rules

Both have modest downsides, but definitely worth doing at least one of them because it's a fairly high risk secondary attack path.

kube2iam downsides:
1. Makes one-way DNAT changes to your iptables rules that remain even if pods are removed
2. Runs as privileged/host network, forcing your kubelet to allow privileged.  PSPs can help here.
3. Operates at the container interface (```cali+```, ```docker0```) and not at the host interface, so a host network pod can "bypass" these iptables rules.

Egress ```networkpolicy``` downsides:
1. Requires K8s ```1.8```+
2. Requires a CNI plugin that implements ```networkpolicy``` policies (```calico```, ```weave```, etc)
3. Requires each namespace be given a ```networkpolicy``` with an ```egress``` ```policytype``` to be effective (so every namespace creation needs to be followed by a ```networkpolicy```)

Upsides:
1. A compromised pod no longer allows direct access to being able to enumerate most resources in the account (including all instance user-data scripts), download/dissect all ECR images, or view certain objects in S3

**Comment by bgeesaman** [comment]
I should add that I'm willing to assist with this effort :-)

**Comment by timothysc** [comment]
@bgeesaman @mattmoyer - we're working on a refresh this week, so happy to entertain PRs on best practices.

**Comment by chuckha** [comment]
I'm looking into generating network policies when namespaces get created.

**Comment by timothysc** [comment]
> Requires each namespace be given a networkpolicy with an egress policytype to be effective (so every namespace creation needs to be followed by a networkpolicy) 

We'd need to add a mutating web-hook, init container, or controller that would apply this policy to every namespace.

**Comment by timothysc** [comment]
So in other conversations, we think it makes more sense to add a simple external component that handles this.  The only other thing we could do is lock down the default namespace.  

thoughts?

**Comment by bgeesaman** [comment]
Considering that this is a _quick_ start and that calico is the default CNI provider, a simple egress policy on only the default namespace seems like the lightest approach that covers the broadest use case.  Documentation notes to cover removing it (if the user needs to) and applying it to other workload namespaces (if the user wants to).  This stops the attack path in the default setup, can be easily removed/modified with one command, and is non-breaking if it is applied and the CNI doesn't yet support egress.

Writing a namespace event watcher/network policy applier to ensure this egress policy is applied to all newly created namespaces seems reasonable but very strongly opinionated.

Kube2IAM is a "drop-in" solution, but it does not clean up the iptables rule if the pods are stopped/removed.  I'd suggest providing the yaml separately and documenting this path if desired along with the SSH command to remove the iptables rules on the nodes to properly "clean up".

Kiam requires mTLS cert generation/distribution between components and really handles a much more advanced use case than a quickstart needs.
