### ISSUE TITLE
Make a CI check that ensures all AMI's are valid

### ISSUE THREAD

**Issue by rdodev** [heptio/aws-quickstart#79]
Recently we had an incident where a user of AWS K8s QS couldn't deploy it because the ami the cluster depends on was not visible/accessible to the public. ~~We should create a "runbook" with manual tests for the `us-west-2` region through an unprivileged account to make sure we didn't miss issues with permissions.~~

We should have a script that checks every image in `RegionMap` within `templates/kubernetes-cluster.template` and ensures each of them:

- Exists
- Is marked as public
- Has the same name (in case one of them isn't the same as the rest... they should all be copied from the same original AMI with the same name)

**Comment by kensimon** [comment]
There already is an automated script that marks all the AMI's public, us-west-2 isn't special and isn't any different.

The reason the us-west-2 AMI was misconfigured was because I manually copied it myself and intentionally patched `deploy-ami.sh` to exclude us-west-2 so I could keep testing it.  This was 100% human error on my part, as I explained in slack.

**Comment by rdodev** [comment]
@kensimon do we have tests automated or otherwise for checking public assets (images, S3 files, etc.) are indeed public in all regions we support?

**Comment by kensimon** [comment]
No, but there is a script that deploys the assets and automatically marks all of them public (deploy-ami.sh)

The issue is that I inserted a `| grep -v us-west-2` into the script manually because I was an idiot.  If we made a script that only audits the existing stuff, it stands to reason I would be an idiot with that script too...

**Comment by rdodev** [comment]
bwahahah, don't be so harsh on yourself. #wereallidiots

**Comment by kensimon** [comment]
Hmm, I think it may be a good idea to add something that loads the whole RegionMap from kubernetes-cluster.template and just ensures all the ami's:

- exist
- are public
- have the same name

and just have that be a part of CI for merging into master.  I'll edit the original message and reopen this.
