### ISSUE TITLE
Update quickstart docs for next cycle

### ISSUE THREAD

**Issue by timothysc** [heptio/aws-quickstart#97]
http://docs.heptio.com/content/aws.html appears out of date and should include a link to https://scanner.heptio.com/ and version update information as well.

**Comment by k8k** [comment]
quick update on this:
- @Bradamant3 is working to get the quickstart content on docs.heptio.com updated and accurate
- the build is slightly broken, but @chuckha has graciously offered to help get it sorted out so we can make sure the changes are live on production for the release thursday of next week
- @Bradamant3 has an email out to Amazon to get changes to the PDF. this process is slow and largely out of our control, but the content tweaks on our end are minor. we do not expect this to be done by the release, and that's fine - the pdf has never been update right on time with releases.

**Comment by timothysc** [comment]
ack, thx for the update!

**Comment by timothysc** [comment]
@Bradamant3 it's a post stand-up validation step to help ensure that their cluster is working properly prior to loading.

**Comment by Bradamant3** [comment]
@timothysc @chuckha @rosskukulinski PTAL. Docs updated on staging site, here (or you can try to follow the not-completely-intuitive navigation):
https://docs-staging.heptio.com/content/aws.html
- updated version
- added link to sonobuoy scanner
https://docs-staging.heptio.com/content/aws-release.html
- updated release notes
https://docs-staging.heptio.com/content/aws-qs-help.html
- added link to troubleshooting.md in quick-start repo. Could not reproduce Ross's issue with deleting PVs (all volumes per cli listed as `"DeleteOnTermination": true`), but can add later if need be.

N.B. Because the QS is in maintenance mode, these updates are minimal.

**Comment by timothysc** [comment]
@Bradamant3 I would nix the reference to kops honestly.  

Otherwise /lgtm 
@chuckha any comments?

**Comment by rosskukulinski** [comment]
@Bradamant3 my only suggestion:

"The QuickStart now includes a default StorageClass, to support the PersistentVolume objects that are required by the Wordpress Helm chart (and by most Helm charts). For more information about the StorageClass and PersistentVolume objects, see the documentation."

==>

"The Quickstart now includes a default StorageClass, to support dynamic provisioning of PersistentVolume objects.  These PersistentVolumes are frequently required by Helm charts, including the Wordpress Chart.  For more information about the StorageClass and PersistentVolume objects, see the documentation."

**Comment by timothysc** [comment]
Closing the issue now, thx @Bradamant3 !
